# NumPy Assignment Questions

In [32]:
# 1. What is a Python library? Why do we use Python libraries?

print("1. What is a Python library? Why do we use Python libraries?\nAns.\n")
print('''Python library is a collection of functions that can be imported as a module in any Pyhton programming. Library contains the 
optimized code of functions that are related and grouped together as a single library, this can be reused by the programmer again and 
again.

Usage of Python libraries increases readability and modularization. They make Python programming easy and simpler without need to write 
the functions from scratch. Libraries save lot of time and effort as the libraries are already well tested and proved.
''')

1. What is a Python library? Why do we use Python libraries?
Ans.

Python library is a collection of functions that can be imported as a module in any Pyhton programming. Library contains the 
optimized code of functions that are related and grouped together as a single library, this can be reused by the programmer again and 
again.

Usage of Python libraries increases readability and modularization. They make Python programming easy and simpler without need to write 
the functions from scratch. Libraries save lot of time and effort as the libraries are already well tested and proved.



In [33]:
# 2. What is the difference between Numpy array and List?

print("2. What is the difference between Numpy array and List?\nAns.\n")
print('''The difference between Numpy array and List are:
    1. Numpy array stores single datatype or homogenous elements. 
       List stores different datatype or heterogenous elements.
    2. Numpy Array has statically defined contiguous memory allocation. It is not dynamic. There is no concept of resizing.
       List has concept of referencing and concept of resizing.
    3. In Numpy Array, as the elements are of the same datatype we need not check the space and datatype but in list, we have 
       to check space and datatype. Hence, arrays are faster than the the list.
''') 

2. What is the difference between Numpy array and List?
Ans.

The difference between Numpy array and List are:
    1. Numpy array stores single datatype or homogenous elements. 
       List stores different datatype or heterogenous elements.
    2. Numpy Array has statically defined contiguous memory allocation. It is not dynamic. There is no concept of resizing.
       List has concept of referencing and concept of resizing.
    3. In Numpy Array, as the elements are of the same datatype we need not check the space and datatype but in list, we have 
       to check space and datatype. Hence, arrays are faster than the the list.



In [34]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

print("3. Find the shape, size and dimension of the following array.\nAns.\n")

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array: \n",arr)
print(f"\nshape = {arr.shape}, size = {arr.size}, dimension = {arr.ndim}")

3. Find the shape, size and dimension of the following array.
Ans.

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape = (3, 4), size = 12, dimension = 2


In [35]:
# 4. Write python code to access the first row of the following array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

print("4. Write python code to access the first row of the following array.\nAns.\n")

import numpy as np

print("Array: \n",arr)
print("\nFirst row of the array :", arr[0])

4. Write python code to access the first row of the following array.
Ans.

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row of the array : [1 2 3 4]


In [36]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

print("5. How do you access the element at the third row and fourth column from the given numpy array?\nAns.\n")

import numpy as np

print("Array: \n",arr)
print("\nElement at the third row and fourth column is: ", arr[2, 3])

5. How do you access the element at the third row and fourth column from the given numpy array?
Ans.

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at the third row and fourth column is:  12


In [37]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

print("6. Write code to extract all odd-indexed elements from the given numpy array?\nAns.\n")

import numpy as np

print("Array: \n",arr)
print("\nAll odd-indexed elements from the given array are: ", arr[::2])

6. Write code to extract all odd-indexed elements from the given numpy array?
Ans.

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

All odd-indexed elements from the given array are:  [[ 1  2  3  4]
 [ 9 10 11 12]]


In [38]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

print("7. How can you generate a random 3x3 matrix with values between 0 and 1?\nAns.\n")

import numpy as np

rand_arr = np.random.rand(3, 3)

print(rand_arr)

7. How can you generate a random 3x3 matrix with values between 0 and 1?
Ans.

[[0.93247012 0.23025363 0.89896749]
 [0.65218296 0.68256396 0.16529189]
 [0.41212328 0.86671753 0.74837174]]


In [40]:
# 8. Describe the difference between np.random.rand and np.random.randn?

print("8. Describe the difference between np.random.rand and np.random.randn?\nAns.")
print('''
np.random.rand() - generates an array of the specified shape filled with random values uniformly distributed between 0 and 1. 
np.random.randn() - generates an array of the specified shape filled with random values as per normal distribution.

Example 1:
''')

import numpy as np

ud_arr = np.random.rand(2, 3)
print("Uniformly ditributed array with random values between 0 and 1:\n", ud_arr)

nd_arr = np.random.randn(2, 3)
print("\nNormally ditributed array with random values:\n", nd_arr)

print("\nExample 2:")

ud_arr = np.random.rand(3, 3)
print("\nUniformly ditributed array with random values between 0 and 1:\n", ud_arr)

nd_arr = np.random.randn(3, 3)
print("\nNormally ditributed array with random values:\n", nd_arr)

8. Describe the difference between np.random.rand and np.random.randn?
Ans.

np.random.rand() - generates an array of the specified shape filled with random values uniformly distributed between 0 and 1. 
np.random.randn() - generates an array of the specified shape filled with random values as per normal distribution.

Example 1:

Uniformly ditributed array with random values between 0 and 1:
 [[0.17059587 0.24657025 0.39738693]
 [0.06748703 0.63066058 0.51421219]]

Normally ditributed array with random values:
 [[ 1.00540979  1.07858981  0.53422397]
 [ 0.59946614 -0.01657203  1.45065817]]

Example 2:

Uniformly ditributed array with random values between 0 and 1:
 [[0.36678156 0.88510581 0.84597759]
 [0.43824686 0.28239626 0.60009465]
 [0.00860484 0.25225713 0.90711345]]

Normally ditributed array with random values:
 [[ 2.30393399 -1.26646703 -1.47517866]
 [-0.07873445  0.27910105  1.03272197]
 [ 0.17658146 -1.32486819 -0.17744545]]


In [41]:
# 9. Write code to increase the dimension of the following array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

print("9. Write code to increase the dimension of the following array?\nAns.")

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original Array: \n",arr,"\nDimension: ",arr.ndim)

#axis=0 is specified, which means that the dimension of the array will be increased along the rows.
exp_row_arr = np.expand_dims(arr, axis=0)
print("\nArray after expanding the dimension along the rows: \n",exp_row_arr, "\nDimension: ", exp_row_arr.ndim)

#axis=1 is specified, which means that the dimension of the array will be increased along the column.
exp_col_arr = np.expand_dims(arr, axis=1)
print("\nArray after expanding the dimension along the column: \n",exp_col_arr, "\nDimension: ", exp_col_arr.ndim)

9. Write code to increase the dimension of the following array?
Ans.
Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
Dimension:  2

Array after expanding the dimension along the rows: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]] 
Dimension:  3

Array after expanding the dimension along the column: 
 [[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]] 
Dimension:  3


In [42]:
# 10. How to transpose the following array in NumPy?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

print("10. How to transpose the following array in NumPy?\nAns.")

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\nArray: \n",arr)

print("\nTranspose of the Array: \n",arr.T)

10. How to transpose the following array in NumPy?
Ans.

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose of the Array: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [43]:
# 11. Consider the following matrix:

#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]]

#Perform the following operation using Python:
#1. Index wise multiplication
#2. Matrix multiplication
#3. Add both the matrics
#4. Subtract matrix B from A
#5. Divide Matrix B by 

print('''11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A
''')

import numpy as np

matrix_A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Ans.\n\nMatrix A2: \n",matrix_A2)
print("\nMatrix B2: \n",matrix_B2)

print("\n1. Index wise multiplication: ")
print(matrix_A2*matrix_B2)
print('''\n2. Matrix multiplication: Throws ValueError since the number of columns of Matrix A2 and number of rows of Matrix B2
do not match''')
#print(matrix_A2@matrix_B2)
print("\n3. Add both the matrics: ")
print(matrix_A2+matrix_B2)
print("\n4. Subtract matrix B from A: ")
print(matrix_A2-matrix_B2)
print("\n5. Divide Matrix B by A ")
print(matrix_B2/matrix_A2)

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8] [9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

Ans.

Matrix A2: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B2: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1. Index wise multiplication: 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication: Throws ValueError since the number of columns of Matrix A2 and number of rows of Matrix B2
do not match

3. Add both the matrics: 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtract matrix B from A: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Divide Matrix B by A 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

print("12. Which function in Numpy can be used to swap the byte order of an array?\nAns.\n")
print("matrix.byteswap() is the method in Numpy that can be used to swap the byte order of an array.\n")

import numpy as np
           
mat = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]') 
print("Matrix: \n",mat)
           
mat_swap = mat.byteswap() 
     
print("\nAfter byte swap: \n",mat_swap)

12. Which function in Numpy can be used to swap the byte order of an array?
Ans.

matrix.byteswap() is the method in Numpy that can be used to swap the byte order of an array.

Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After byte swap: 
 [[ 72057594037927936 144115188075855872 216172782113783808]
 [288230376151711744 360287970189639680 432345564227567616]
 [504403158265495552 576460752303423488 648518346341351424]]


In [45]:
# 13. What is the significance of the np.linalg.inv function?

print("13. What is the significance of the np.linalg.inv function?\nAns.\n")
print('''np.linalg.inv() is used to calculate the inverse of the matrix.

For Exmaple - 
''')

arr = np.array([[1, 2, 3], [-1, 3, 6], [-2, 8, 1]])
print("Matrix: \n",arr)

print("\nInverse of the matrix is: \n", np.linalg.inv(arr))

13. What is the significance of the np.linalg.inv function?
Ans.

np.linalg.inv() is used to calculate the inverse of the matrix.

For Exmaple - 

Matrix: 
 [[ 1  2  3]
 [-1  3  6]
 [-2  8  1]]

Inverse of the matrix is: 
 [[ 0.61643836 -0.30136986 -0.04109589]
 [ 0.15068493 -0.09589041  0.12328767]
 [ 0.02739726  0.16438356 -0.06849315]]


In [46]:
# 14. What does the np.reshape function do, and how is it used?

print("14. What does the np.reshape function do, and how is it used?\nAns.")

print("\nnp.reshape function changes the shape of the Array. without changing the data\n\nExample -\n")

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Array : \n",arr)

print("\nReshape of the array: \n",np.reshape(arr, (4, 2)))

14. What does the np.reshape function do, and how is it used?
Ans.

np.reshape function changes the shape of the Array. without changing the data

Example -

Array : 
 [[1 2 3 4]
 [5 6 7 8]]

Reshape of the array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
# 15. What is broadcasting in Numpy?

print("15. What is broadcasting in Numpy?\nAns.\n")

print('''Broadcasting is a very reliable feature offered by the NumPy library in Python. The term broadcasting refers to the ability 
of NumPy to treat arrays with different dimensions during arithmetic operations.

For example - Some of the Broadcasting Operations
''')

import numpy as np 
  
v = np.array([1, 2, 3])   
w = np.array([4, 5])
print("2 Vectors: Vector1 - ",v,"Vector2: ",w)
  
print("\n1. Outer product of vectors Vector1 and Vector2:")
print(np.reshape(v, (3, 1)) * w) 
  
x = np.array([[1, 2, 3], [4, 5, 6]]) 
  
print("\n2. Broadcasting vector", v, "to matrix :\n", x)
print("\n",x + v) 
  
print("\n3. Broadcasting vector", w, "to the transposed matrix: \n",x) 
print("\n",(x.T + w).T) 
  
print("\n4. Reshaping vector", w," and broadcasting to matrix: \n",x )
print("\n",x + np.reshape(w, (2, 1))) 
  
print("\n5. Broadcasting scalar multiplication Matrix*2: \n", x) 
print("\n",x * 2) 

15. What is broadcasting in Numpy?
Ans.

Broadcasting is a very reliable feature offered by the NumPy library in Python. The term broadcasting refers to the ability 
of NumPy to treat arrays with different dimensions during arithmetic operations.

For example - Some of the Broadcasting Operations

2 Vectors: Vector1 -  [1 2 3] Vector2:  [4 5]

1. Outer product of vectors Vector1 and Vector2:
[[ 4  5]
 [ 8 10]
 [12 15]]

2. Broadcasting vector [1 2 3] to matrix :
 [[1 2 3]
 [4 5 6]]

 [[2 4 6]
 [5 7 9]]

3. Broadcasting vector [4 5] to the transposed matrix: 
 [[1 2 3]
 [4 5 6]]

 [[ 5  6  7]
 [ 9 10 11]]

4. Reshaping vector [4 5]  and broadcasting to matrix: 
 [[1 2 3]
 [4 5 6]]

 [[ 5  6  7]
 [ 9 10 11]]

5. Broadcasting scalar multiplication Matrix*2: 
 [[1 2 3]
 [4 5 6]]

 [[ 2  4  6]
 [ 8 10 12]]
